(function() {var implementors = {};
implementors["typenum"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='typenum/int/struct.Z0.html' title='typenum::int::Z0'>Z0</a>","impl&lt;U:&nbsp;<a class='trait' href='typenum/marker_traits/trait.Unsigned.html' title='typenum::marker_traits::Unsigned'>Unsigned</a> + <a class='trait' href='typenum/marker_traits/trait.NonZero.html' title='typenum::marker_traits::NonZero'>NonZero</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='typenum/int/struct.PInt.html' title='typenum::int::PInt'>PInt</a>&lt;U&gt;","impl&lt;U:&nbsp;<a class='trait' href='typenum/marker_traits/trait.Unsigned.html' title='typenum::marker_traits::Unsigned'>Unsigned</a> + <a class='trait' href='typenum/marker_traits/trait.NonZero.html' title='typenum::marker_traits::NonZero'>NonZero</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='typenum/int/struct.NInt.html' title='typenum::int::NInt'>NInt</a>&lt;U&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='typenum/array/struct.ATerm.html' title='typenum::array::ATerm'>ATerm</a>","impl&lt;V,&nbsp;A&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='typenum/array/struct.TArr.html' title='typenum::array::TArr'>TArr</a>&lt;V,&nbsp;A&gt; <span class='where'>where V: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a>, A: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
