(function() {var implementors = {};
implementors["typenum"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='typenum/bit/struct.B0.html' title='typenum::bit::B0'>B0</a>&gt; for <a class='struct' href='typenum/bit/struct.B0.html' title='typenum::bit::B0'>B0</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='typenum/bit/struct.B0.html' title='typenum::bit::B0'>B0</a>&gt; for <a class='struct' href='typenum/bit/struct.B1.html' title='typenum::bit::B1'>B1</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='typenum/bit/struct.B1.html' title='typenum::bit::B1'>B1</a>&gt; for <a class='struct' href='typenum/bit/struct.B0.html' title='typenum::bit::B0'>B0</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='typenum/bit/struct.B1.html' title='typenum::bit::B1'>B1</a>&gt; for <a class='struct' href='typenum/bit/struct.B1.html' title='typenum::bit::B1'>B1</a>","impl&lt;Ur:&nbsp;<a class='trait' href='typenum/marker_traits/trait.Unsigned.html' title='typenum::marker_traits::Unsigned'>Unsigned</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;Ur&gt; for <a class='struct' href='typenum/uint/struct.UTerm.html' title='typenum::uint::UTerm'>UTerm</a>","impl&lt;Ul:&nbsp;<a class='trait' href='typenum/marker_traits/trait.Unsigned.html' title='typenum::marker_traits::Unsigned'>Unsigned</a>,&nbsp;Bl:&nbsp;<a class='trait' href='typenum/marker_traits/trait.Bit.html' title='typenum::marker_traits::Bit'>Bit</a>,&nbsp;Ur:&nbsp;<a class='trait' href='typenum/marker_traits/trait.Unsigned.html' title='typenum::marker_traits::Unsigned'>Unsigned</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;Ur&gt; for <a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul,&nbsp;Bl&gt; <span class='where'>where <a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul,&nbsp;Bl&gt;: PrivateXor&lt;Ur&gt;, PrivateXorOut&lt;<a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul,&nbsp;Bl&gt;,&nbsp;Ur&gt;: Trim</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
